---
include:
  - board: nice_nano
    shield: tester_pro_micro

  - board: seeeduino_xiao_ble
    shield: tester_xiao

  - board: nice_nano
    shield: cosmotyl_left_test
    artifact-name: cosmotyl-left-test
